-- Phase 10 migration 8.
-- Position pings are append-only events. The parties.pings and parties.ping_log
-- jsonb columns remain as a compatibility fallback for older deployments, but
-- new clients write here so two teammates cannot overwrite each other's arrays.

create table if not exists public.party_ping_events (
  id              bigint generated by default as identity primary key,
  party_id        bigint not null references public.parties(id) on delete cascade,
  raid_id         bigint not null,
  user_id         uuid not null references auth.users(id) on delete cascade,
  callsign        text not null,
  source_event_id text not null,
  map_norm        text not null,
  x               double precision not null,
  y               double precision not null,
  z               double precision not null,
  yaw             double precision not null default 0,
  taps            smallint not null default 1 check (taps between 1 and 3),
  client_at      bigint not null,
  server_at      timestamptz not null default now(),
  unique (party_id, user_id, source_event_id)
);

create index if not exists party_ping_events_raid_idx
  on public.party_ping_events (party_id, raid_id, server_at desc);

alter table public.party_ping_events enable row level security;

drop policy if exists "Party ping events member read" on public.party_ping_events;
create policy "Party ping events member read" on public.party_ping_events
  for select using (public.is_party_member(party_id, auth.uid()));

revoke all on table public.party_ping_events from anon, authenticated;
grant select on table public.party_ping_events to authenticated;

create or replace function public.append_party_ping(
  p_code text,
  p_raid_id bigint,
  p_ping jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_party_id bigint;
  v_raid_id bigint;
  v_callsign text;
  v_event_id text;
  v_row public.party_ping_events%rowtype;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;

  select p.id, p.raid_id, pm.callsign
    into v_party_id, v_raid_id, v_callsign
  from public.parties p
  join public.party_members pm
    on pm.party_id = p.id and pm.user_id = auth.uid()
  where p.code = p_code;

  if v_party_id is null then raise exception 'not a party member'; end if;
  if v_raid_id <> p_raid_id then raise exception 'raid has changed'; end if;

  v_event_id := nullif(trim(p_ping->>'id'), '');
  if v_event_id is null then raise exception 'ping id is required'; end if;
  if lower(trim(coalesce(p_ping->>'map', ''))) not in (
    'customs', 'woods', 'interchange', 'shoreline', 'factory',
    'lighthouse', 'streets-of-tarkov', 'reserve', 'ground-zero', 'the-lab'
  ) then
    raise exception 'unsupported map';
  end if;

  -- Two tabs can hear the same four-character Remote ID and stamp different
  -- client event ids for the same screenshot. Serialize this user's append
  -- window and reuse an event that is effectively identical within five seconds.
  -- The client already folds intentional multi-taps into one event, so this
  -- protects against duplicate tabs without hiding a real later position.
  perform pg_advisory_xact_lock(hashtext(v_party_id::text || ':' || auth.uid()::text));

  select * into v_row
  from public.party_ping_events
  where party_id = v_party_id
    and raid_id = v_raid_id
    and user_id = auth.uid()
    and (
      source_event_id = v_event_id
      or (
        abs(client_at - (p_ping->>'at')::bigint) <= 5000
        and map_norm = lower(trim(coalesce(p_ping->>'map', '')))
        and abs(x - (p_ping->>'x')::double precision) <= 0.01
        and abs(y - (p_ping->>'y')::double precision) <= 0.01
        and abs(z - (p_ping->>'z')::double precision) <= 0.01
      )
    )
  order by server_at desc
  limit 1;

  if not found then
    insert into public.party_ping_events (
      party_id, raid_id, user_id, callsign, source_event_id, map_norm,
      x, y, z, yaw, taps, client_at
    ) values (
      v_party_id,
      v_raid_id,
      auth.uid(),
      v_callsign,
      v_event_id,
      lower(trim(coalesce(p_ping->>'map', ''))),
      (p_ping->>'x')::double precision,
      (p_ping->>'y')::double precision,
      (p_ping->>'z')::double precision,
      coalesce((p_ping->>'yaw')::double precision, 0),
      least(greatest(coalesce((p_ping->>'taps')::integer, 1), 1), 3)::smallint,
      (p_ping->>'at')::bigint
    )
    on conflict (party_id, user_id, source_event_id) do nothing;

    select * into v_row
    from public.party_ping_events
    where party_id = v_party_id
      and user_id = auth.uid()
      and source_event_id = v_event_id;
  end if;

  update public.parties set last_active_at = now() where id = v_party_id;

  return jsonb_build_object(
    'id', v_row.id,
    'source_event_id', v_row.source_event_id,
    'party_id', v_row.party_id,
    'raid_id', v_row.raid_id,
    'user_id', v_row.user_id,
    'user', v_row.callsign,
    'callsign', v_row.callsign,
    'map_norm', v_row.map_norm,
    'x', v_row.x, 'y', v_row.y, 'z', v_row.z, 'yaw', v_row.yaw,
    'taps', v_row.taps, 'client_at', v_row.client_at,
    'server_at', v_row.server_at
  );
end;
$$;

create or replace function public.clear_party_ping_events(
  p_code text,
  p_raid_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_party_id bigint;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  select p.id into v_party_id
  from public.parties p
  join public.party_members pm
    on pm.party_id = p.id and pm.user_id = auth.uid()
  where p.code = p_code and p.raid_id = p_raid_id;
  if v_party_id is null then raise exception 'not a party member'; end if;
  delete from public.party_ping_events where party_id = v_party_id and raid_id = p_raid_id;
end;
$$;

revoke all on function public.append_party_ping(text, bigint, jsonb) from public;
revoke all on function public.clear_party_ping_events(text, bigint) from public;
grant execute on function public.append_party_ping(text, bigint, jsonb) to authenticated;
grant execute on function public.clear_party_ping_events(text, bigint) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'party_ping_events'
  ) then
    alter publication supabase_realtime add table public.party_ping_events;
  end if;
end $$;
