-- Phase 10 migration 7 of 7.
-- Prerequisite: 10_06_user_settings.sql and all earlier Phase 10 files.
--
-- R3 is intentionally destructive. The live friendships shape is callsign-keyed
-- and is not reconstructed. Full-reset users are re-registered, so replace it
-- with the stable auth-user shape below.

drop function if exists public.get_friend_parties(text[]);
drop function if exists public.get_friend_parties(uuid[]);
drop table if exists public.friendships cascade;

create table public.friendships (
  id           bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status       text not null default 'pending',
  created_at   timestamptz not null default now(),
  check (requester_id <> addressee_id),
  check (status in ('pending', 'accepted')),
  unique (requester_id, addressee_id)
);

alter table public.friendships enable row level security;

create policy "Friendships participants read" on public.friendships
  for select using (
    auth.uid() = requester_id or auth.uid() = addressee_id
  );

create policy "Friendships requester insert" on public.friendships
  for insert with check (
    auth.uid() = requester_id
    and requester_id <> addressee_id
    and status in ('pending', 'accepted')
  );

create policy "Friendships participants update" on public.friendships
  for update using (
    auth.uid() = requester_id or auth.uid() = addressee_id
  ) with check (
    (auth.uid() = requester_id or auth.uid() = addressee_id)
    and status in ('pending', 'accepted')
  );

create policy "Friendships participants delete" on public.friendships
  for delete using (
    auth.uid() = requester_id or auth.uid() = addressee_id
  );

-- RLS gates which friendship rows a participant may touch; GRANT gates which
-- columns it may update. Keep endpoint identities immutable to the client.
revoke update on table public.friendships from anon, authenticated;
grant update (status) on table public.friendships to anon, authenticated;

-- Returns a current party code for each accepted friend supplied by the caller.
-- Callsigns are resolved here for display; they are not identity keys.
create or replace function public.get_friend_parties(p_user_ids uuid[])
returns table(user_id uuid, callsign text, code text)
language sql
security definer
set search_path = public
as $$
  select distinct on (pm.user_id)
    pm.user_id,
    p.callsign,
    party.code
  from public.friendships f
  join public.party_members pm
    on pm.user_id = case
      when f.requester_id = auth.uid() then f.addressee_id
      else f.requester_id
    end
  join public.profiles p on p.id = pm.user_id
  join public.parties party on party.id = pm.party_id
  where auth.uid() is not null
    and f.status = 'accepted'
    and (f.requester_id = auth.uid() or f.addressee_id = auth.uid())
    and pm.user_id = any(coalesce(p_user_ids, array[]::uuid[]))
  order by pm.user_id, party.created_at desc;
$$;

revoke all on function public.get_friend_parties(uuid[]) from public;
grant execute on function public.get_friend_parties(uuid[]) to authenticated;
