-- Curated corrections for the derived quest shareability model.
create table if not exists public.quest_share_overrides (
  id          bigint generated by default as identity primary key,
  task_id     text not null,
  task_name   text,
  verdict     text not null check (verdict in ('shared', 'partial', 'solo')),
  note        text,
  updated_at  timestamptz default now(),
  unique (task_id)
);

alter table public.quest_share_overrides enable row level security;
drop policy if exists "quest_share_overrides public read" on public.quest_share_overrides;
drop policy if exists "quest_share_overrides admin write" on public.quest_share_overrides;
create policy "quest_share_overrides public read" on public.quest_share_overrides
  for select using (auth.uid() is not null);
create policy "quest_share_overrides admin write" on public.quest_share_overrides
  for all
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.is_admin));

insert into public.quest_share_overrides (task_id, task_name, verdict, note) values
  ('5bc4776586f774512d07cf05', 'The Tarkov Shooter - Part 1', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('5bc479e586f7747f376c7da3', 'The Tarkov Shooter - Part 2', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('5bc47dbf86f7741ee74e93b9', 'The Tarkov Shooter - Part 3', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('5bc480a686f7741af0342e29', 'The Tarkov Shooter - Part 4', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('5bc4826c86f774106d22d88b', 'The Tarkov Shooter - Part 5', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('5bc4836986f7740c0152911c', 'The Tarkov Shooter - Part 5', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('5bc4856986f77454c317bea7', 'The Tarkov Shooter - Part 6', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('5bc4893c86f774626f5ebf3e', 'The Tarkov Shooter - Part 7', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('59c512ad86f7741f0d09de9b', 'The Punisher - Part 1', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('59c50a9e86f7745fef66f4ff', 'The Punisher - Part 2', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('59c50c8886f7745fed3193bf', 'The Punisher - Part 3', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('59ca264786f77445a80ed044', 'The Punisher - Part 4', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('59ca29fb86f77445ab465c87', 'The Punisher - Part 5', 'solo', 'Named solo-only chain from patch 1.1 notes.'),
  ('59ca2eb686f77445a80ed049', 'The Punisher - Part 6', 'solo', 'Named solo-only chain from patch 1.1 notes.')
on conflict (task_id) do nothing;
