-- Crowdsourced cooperative-quest data.
--
-- 10_27 added the curated tier, but tarkov.help marks only 5 of 562 quests and
-- nothing upstream publishes this at all. The players who actually run these
-- raids are the ones who can see a teammate's kill tick their counter, so this
-- table lets them record it as they play.
--
-- Reports are per OBJECTIVE, never per task. That is the unit a player can
-- actually observe ("I shot it, their counter moved"), and the task-level
-- shared/partial/solo roll-up is already derived in src/questShare.js. Asking a
-- player to judge a whole task would be asking them to guess.
--
-- One row per (user, objective): re-reporting updates your own vote rather than
-- stuffing the ballot.

create table if not exists public.quest_share_reports (
  id           bigint generated by default as identity primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  task_id      text not null,
  objective_id text not null,
  verdict      text not null check (verdict in ('squad', 'personal')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (user_id, task_id, objective_id)
);

create index if not exists quest_share_reports_objective_idx
  on public.quest_share_reports (task_id, objective_id);

alter table public.quest_share_reports enable row level security;

-- A reporter owns their own row and can see, change or retract it. Nobody reads
-- anyone else's: who voted which way is not information this feature needs to
-- expose, and the aggregate below is served without it.
drop policy if exists "Quest share reports own select" on public.quest_share_reports;
drop policy if exists "Quest share reports own insert" on public.quest_share_reports;
drop policy if exists "Quest share reports own update" on public.quest_share_reports;
drop policy if exists "Quest share reports own delete" on public.quest_share_reports;

create policy "Quest share reports own select" on public.quest_share_reports
  for select using (auth.uid() = user_id);
create policy "Quest share reports own insert" on public.quest_share_reports
  for insert with check (auth.uid() = user_id);
create policy "Quest share reports own update" on public.quest_share_reports
  for update using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create policy "Quest share reports own delete" on public.quest_share_reports
  for delete using (auth.uid() = user_id);

-- The tally is the only path to other people's reports, and it returns counts
-- with no user ids attached. SECURITY DEFINER because the select policy above
-- deliberately hides every row the caller did not write.
create or replace function public.quest_share_tallies()
returns table (
  task_id        text,
  objective_id   text,
  squad_count    integer,
  personal_count integer
)
language sql
security definer
stable
set search_path = public
as $$
  select
    r.task_id,
    r.objective_id,
    count(*) filter (where r.verdict = 'squad')::integer,
    count(*) filter (where r.verdict = 'personal')::integer
  from public.quest_share_reports r
  group by r.task_id, r.objective_id;
$$;

revoke all on function public.quest_share_tallies() from public;
grant execute on function public.quest_share_tallies() to authenticated;

-- Casting a vote goes through an RPC so the upsert cannot be aimed at another
-- user: user_id is taken from the session, never from the caller's payload.
-- Passing a null verdict retracts the vote.
create or replace function public.report_quest_share(
  p_task_id      text,
  p_objective_id text,
  p_verdict      text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  if p_task_id is null or p_objective_id is null then
    raise exception 'task and objective are required';
  end if;

  if p_verdict is null then
    delete from public.quest_share_reports
    where user_id = auth.uid() and task_id = p_task_id and objective_id = p_objective_id;
    return;
  end if;

  if p_verdict not in ('squad', 'personal') then
    raise exception 'verdict must be squad or personal';
  end if;

  insert into public.quest_share_reports (user_id, task_id, objective_id, verdict)
  values (auth.uid(), p_task_id, p_objective_id, p_verdict)
  on conflict (user_id, task_id, objective_id) do update set
    verdict    = excluded.verdict,
    updated_at = now();
end;
$$;

revoke all on function public.report_quest_share(text, text, text) from public;
grant execute on function public.report_quest_share(text, text, text) to authenticated;

-- Table privileges. A reader needs SELECT to see how they themselves voted (the
-- own-row policy above scopes it); every write goes through report_quest_share,
-- which is SECURITY DEFINER and so needs no DML grant of its own. Withholding
-- INSERT/UPDATE/DELETE means the only way to create a row is the RPC that stamps
-- user_id from the session -- the payload can never aim a vote at someone else.
-- The write policies above are kept as a second lock: if a DML grant is ever
-- added, they still confine it to own rows rather than opening the table.
revoke all on table public.quest_share_reports from anon, authenticated;
grant select on table public.quest_share_reports to authenticated;
