-- Phase 10A migration 7 of 7.
-- Prerequisite: 10a_06_user_settings.sql and all earlier Phase 10A files.
-- The friendships table and get_friend_parties function below are reconstructed
-- from src/useFriends.js because their live definitions were not present in the
-- repository. The owner must diff them against the live schema before applying.

-- RECONSTRUCTED DEFINITION: callsign-keyed friendships used by useFriends.js.
create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid references auth.users(id) on delete cascade not null,
  requester_callsign text not null,
  addressee_callsign text not null,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  unique (requester_id, addressee_callsign)
);

alter table public.friendships enable row level security;

drop policy if exists "Friendships participants read" on public.friendships;
drop policy if exists "Friendships requester insert" on public.friendships;
drop policy if exists "Friendships addressee update" on public.friendships;
drop policy if exists "Friendships participants delete" on public.friendships;

create policy "Friendships participants read" on public.friendships
  for select using (
    auth.uid() = requester_id
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.callsign = friendships.addressee_callsign
    )
  );

create policy "Friendships requester insert" on public.friendships
  for insert with check (auth.uid() = requester_id);

create policy "Friendships addressee update" on public.friendships
  for update using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.callsign = friendships.addressee_callsign
    )
  ) with check (status in ('pending', 'accepted'));

create policy "Friendships participants delete" on public.friendships
  for delete using (
    auth.uid() = requester_id
    or exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.callsign = friendships.addressee_callsign
    )
  );

-- RECONSTRUCTED DEFINITION: returns current party codes for accepted friends.
drop function if exists public.get_friend_parties(text[]);
create or replace function public.get_friend_parties(p_callsigns text[])
returns table(callsign text, code text)
language sql
security definer
set search_path = public
as $$
  select pm.callsign, p.code
  from public.party_members pm
  join public.parties p on p.id = pm.party_id
  where auth.uid() is not null
    and pm.callsign = any(coalesce(p_callsigns, array[]::text[]))
    and exists (
      select 1
      from public.friendships f
      where f.status = 'accepted'
        and (
          (f.requester_id = auth.uid() and f.addressee_callsign = pm.callsign)
          or (
            f.requester_callsign = pm.callsign
            and exists (
              select 1 from public.profiles me
              where me.id = auth.uid() and me.callsign = f.addressee_callsign
            )
          )
        )
    );
$$;

revoke all on function public.get_friend_parties(text[]) from public;
grant execute on function public.get_friend_parties(text[]) to authenticated;

