-- Run this in the Supabase SQL editor (Dashboard → SQL Editor → New query)
-- If you already ran the previous schema, run only the ALTER TABLE lines at the bottom.

create table if not exists public.parties (
  id         bigint generated by default as identity primary key,
  code       text unique not null,
  leader     text not null,
  map_id     text,
  map_name   text,
  map_norm   text,
  members    jsonb not null default '{}',
  spawn      text,
  progress   jsonb not null default '{}',
  starred    jsonb not null default '{}',
  created_at timestamptz default now()
);

alter table public.parties enable row level security;

create policy "Public read"   on public.parties for select using (true);
create policy "Public insert" on public.parties for insert with check (true);
create policy "Public update" on public.parties for update using (true);

alter publication supabase_realtime add table public.parties;

-- If upgrading an existing table, run these two lines instead:
-- alter table public.parties add column if not exists progress jsonb not null default '{}';
-- alter table public.parties add column if not exists starred jsonb not null default '{}';
