-- ============================================================
-- Run the entire contents of this file in Supabase SQL Editor
-- Dashboard → SQL Editor → New query → paste → Run
-- ============================================================

-- Parties table (create or update existing)
create table if not exists public.parties (
  id         bigint generated by default as identity primary key,
  code       text unique not null,
  leader     text not null,
  map_id     text,
  map_name   text,
  map_norm   text,
  members    jsonb not null default '{}',
  spawn      text,
  progress   jsonb not null default '{}',
  starred    jsonb not null default '{}',
  created_at timestamptz default now()
);

-- Add new columns to parties if upgrading
alter table public.parties add column if not exists progress jsonb not null default '{}';
alter table public.parties add column if not exists starred  jsonb not null default '{}';

-- User quests — one row per saved quest per user
create table if not exists public.user_quests (
  id         bigint generated by default as identity primary key,
  user_id    uuid references auth.users(id) on delete cascade not null,
  quest_id   text not null,
  quest_name text not null,
  map_norm   text,           -- null means "any map"
  important  boolean not null default false,
  created_at timestamptz default now(),
  unique (user_id, quest_id)
);

-- User profiles — stores the display name / callsign chosen at registration
create table if not exists public.profiles (
  id         uuid references auth.users(id) on delete cascade primary key,
  callsign   text unique not null,
  created_at timestamptz default now()
);

-- ── Row Level Security ──────────────────────────────────────

alter table public.parties     enable row level security;
alter table public.user_quests enable row level security;
alter table public.profiles    enable row level security;

-- Parties: anyone can read/insert/update (code is the access control)
drop policy if exists "Parties public read"   on public.parties;
drop policy if exists "Parties public insert" on public.parties;
drop policy if exists "Parties public update" on public.parties;
create policy "Parties public read"   on public.parties for select using (true);
create policy "Parties public insert" on public.parties for insert with check (true);
create policy "Parties public update" on public.parties for update using (true);

-- User quests: users can only see and edit their own
drop policy if exists "User quests select" on public.user_quests;
drop policy if exists "User quests insert" on public.user_quests;
drop policy if exists "User quests update" on public.user_quests;
drop policy if exists "User quests delete" on public.user_quests;
create policy "User quests select" on public.user_quests for select using (auth.uid() = user_id);
create policy "User quests insert" on public.user_quests for insert with check (auth.uid() = user_id);
create policy "User quests update" on public.user_quests for update using (auth.uid() = user_id);
create policy "User quests delete" on public.user_quests for delete using (auth.uid() = user_id);

-- Profiles: users can read all (for callsign display), edit only their own
drop policy if exists "Profiles public read"  on public.profiles;
drop policy if exists "Profiles own update"   on public.profiles;
drop policy if exists "Profiles own insert"   on public.profiles;
create policy "Profiles public read" on public.profiles for select using (true);
create policy "Profiles own insert"  on public.profiles for insert with check (auth.uid() = id);
create policy "Profiles own update"  on public.profiles for update using (auth.uid() = id);

-- Real-time on parties
alter publication supabase_realtime add table public.parties;

-- Auto-cleanup parties older than 48 hours (run manually or via pg_cron)
-- delete from public.parties where created_at < now() - interval '48 hours';
