#!/usr/bin/env bash
#
# Capture the live public catalog into an output directory as replayable SQL,
# so the probes under supabase/probes/ can be rehearsed against a faithful copy.
#
# READ-ONLY against the linked project. Every statement here is catalog
# observation, which docs/supabase-database-workflow.md sanctions and requires:
# ownership, rolbypassrls, live routine bodies, grants and policy definitions
# exist nowhere else. It issues no write, no `set role`, no begin-wrapped
# fixture, and it persists no credential.
#
# The four .sql files it writes are a production catalog capture. Keep them
# OUTSIDE the repository -- that is why the output directory defaults to a temp
# path, and why only this script plus the hand-written bootstrap and seed are
# committed.
#
#   ./capture-live-catalog.sh [output-directory]
#
# Requires the Supabase CLI logged in and linked (`supabase db query --linked`
# must work from the repository root) and python3 to decode the JSON envelope.

set -euo pipefail
OUT="${1:-${TMPDIR:-/tmp}/tsp-harness}"
mkdir -p "$OUT"
# python here is the Windows interpreter, which cannot open an MSYS /c/... path.
# `pwd -W` hands back the C:/... form; the fallback covers a real POSIX shell.
OUTW="$(cd "$OUT" && { pwd -W 2>/dev/null || pwd; })"
SQLDIR="$(mktemp -d)"
trap 'rm -rf "$SQLDIR"' EXIT

emit() {
  # emit <name> <sql-file>: run the query, pull the single text column out of
  # the JSON envelope, write <name>.sql.
  supabase db query "$(cat "$2")" --linked 2>/dev/null > "$OUT/$1.json"
  python -c "
import json
t = open(r'$OUTW/$1.json', encoding='utf-8').read()
d = json.loads(t[t.index('{'):])
s = (d['rows'][0]['d'] or '').replace(chr(13), '')
open(r'$OUTW/$1.sql', 'w', encoding='utf-8', newline='\n').write(s)
print('  $1.sql', len(s), 'bytes')
"
}

# --- tables: DDL, constraints, RLS enable/force -----------------------------
# attidentity is essential. pg_attrdef carries no default for an identity
# column, so a naive capture emits `id bigint not null` and every insert that
# relies on the identity fails with a not-null violation.
cat > "$SQLDIR/tables.sql" <<'PGEOF'
with tabs as (
  select string_agg(x.ddl, E'\n' order by x.tn) d from (
    select c.relname tn,
      'create table public.'||quote_ident(c.relname)||E' (\n  '||
      string_agg(quote_ident(a.attname)||' '||format_type(a.atttypid,a.atttypmod)||
        coalesce(' default '||pg_get_expr(ad.adbin,ad.adrelid),'')||
        case when a.attidentity <> '' then ' generated by default as identity' else '' end||
        case when a.attnotnull then ' not null' else '' end, E',\n  ' order by a.attnum)
      ||E'\n);' as ddl
    from pg_class c join pg_namespace n on n.oid=c.relnamespace
    join pg_attribute a on a.attrelid=c.oid and a.attnum>0 and not a.attisdropped
    left join pg_attrdef ad on ad.adrelid=c.oid and ad.adnum=a.attnum
    where n.nspname='public' and c.relkind='r'
    group by c.relname
  ) x
), cons as (
  select string_agg('alter table public.'||quote_ident(cl.relname)||' add constraint '||
    quote_ident(k.conname)||' '||pg_get_constraintdef(k.oid)||';', E'\n'
    order by case k.contype when 'p' then 1 when 'u' then 2 when 'c' then 3 else 4 end,
             cl.relname, k.conname) d
  from pg_constraint k join pg_class cl on cl.oid=k.conrelid
  join pg_namespace n on n.oid=cl.relnamespace where n.nspname='public'
), rls as (
  select string_agg('alter table public.'||quote_ident(c.relname)||' enable row level security;'||
    case when c.relforcerowsecurity
         then E'\nalter table public.'||quote_ident(c.relname)||' force row level security;'
         else '' end, E'\n' order by c.relname) d
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public' and c.relkind='r' and c.relrowsecurity
)
select (select d from tabs)||E'\n\n'||(select d from cons)||E'\n\n'||(select d from rls) as d;
PGEOF

# --- functions: bodies plus ACLs --------------------------------------------
# pg_get_functiondef emits no trailing semicolon, hence the appended E'\n;'.
# The ACLs must be mirrored too: Postgres defaults a new function to EXECUTE TO
# PUBLIC, while live carries explicit ACLs with no PUBLIC entry. Without them,
# "anon cannot execute this RPC" passes for a harness reason rather than a real
# one. Do not blanket-revoke instead: is_party_member and current_profile must
# stay executable by authenticated or every policy that calls them silently
# returns zero rows.
cat > "$SQLDIR/functions.sql" <<'PGEOF'
with defs as (
  select string_agg(pg_get_functiondef(p.oid)||E'\n;', E'\n\n' order by p.proname, p.oid) d
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.prokind in ('f','p')
), acl as (
  select string_agg(a.stmt, E'\n' order by a.stmt) d from (
    select distinct 'revoke all on function public.'||p.proname||
      '('||pg_get_function_identity_arguments(p.oid)||') from public;' as stmt
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.prokind in ('f','p')
    union all
    select distinct 'grant execute on function public.'||p.proname||
      '('||pg_get_function_identity_arguments(p.oid)||') to '||quote_ident(r.grantee)||';'
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    cross join (values ('anon'),('authenticated'),('service_role')) r(grantee)
    where n.nspname='public' and p.prokind in ('f','p')
      and has_function_privilege(r.grantee, p.oid, 'execute')
  ) a
)
select (select d from defs)||E'\n\n'||(select d from acl) as d;
PGEOF

# --- policies ---------------------------------------------------------------
# quote_ident on the policy name, not quote_literal: the names carry spaces and
# CREATE POLICY wants an identifier.
cat > "$SQLDIR/policies.sql" <<'PGEOF'
select string_agg(
  'create policy '||quote_ident(policyname)||' on public.'||quote_ident(tablename)||
  ' as '||permissive||' for '||cmd||' to '||array_to_string(roles, ', ')||
  coalesce(' using ('||qual||')','')||
  coalesce(' with check ('||with_check||')','')||';', E'\n'
  order by tablename, policyname) as d
from pg_policies where schemaname='public';
PGEOF

# --- grants -----------------------------------------------------------------
# Column-level grants are the point. authenticated held UPDATE on eleven named
# columns of public.parties -- progress among them -- while table_privileges
# showed nothing at all. A harness built without them reports a denial that
# production does not make, which is how that hole stayed hidden.
cat > "$SQLDIR/grants.sql" <<'PGEOF'
with tg as (
  select string_agg('grant '||privilege_type||' on table public.'||quote_ident(table_name)||
    ' to '||quote_ident(grantee)||';', E'\n'
    order by table_name, grantee, privilege_type) d
  from information_schema.table_privileges
  where table_schema='public' and grantee in ('anon','authenticated','service_role')
), cg as (
  select string_agg('grant '||privilege_type||' ('||cols||') on table public.'||
    quote_ident(table_name)||' to '||quote_ident(grantee)||';', E'\n'
    order by table_name, grantee, privilege_type) d
  from (
    select cp.table_name, cp.grantee, cp.privilege_type,
           string_agg(quote_ident(cp.column_name),', ' order by cp.column_name) cols
    from information_schema.column_privileges cp
    where cp.table_schema='public' and cp.grantee in ('anon','authenticated','service_role')
      and not exists (
        select 1 from information_schema.table_privileges tp
        where tp.table_schema=cp.table_schema and tp.table_name=cp.table_name
          and tp.grantee=cp.grantee and tp.privilege_type=cp.privilege_type)
    group by 1,2,3
  ) z
)
select coalesce((select d from tg),'')||E'\n'||coalesce((select d from cg),'') as d;
PGEOF

echo "Capturing the live public catalog (read-only)..."
emit 01_tables    "$SQLDIR/tables.sql"
emit 01b_functions "$SQLDIR/functions.sql"
emit 04_policies  "$SQLDIR/policies.sql"
emit 05_grants    "$SQLDIR/grants.sql"

echo
echo "Captured to $OUT."
echo "Against the 2026-09-03 catalog this reproduces:"
echo "  17 tables, 81 constraints, 37 policies, 47 routines."
echo "Keep that directory outside the repository."
