// Battle Pass Intel, legacy intel-loot and curated document spawns.
//
// Pure helpers shared by the intel hook (shaping), MapLeaflet (rendering and
// proximity) and StartRaidModal (the pre-raid brief). No React, no side effects.
//
// Three sources feed the same shape:
//
//   battlepass src/data/prebaked/battlepass-intel.json — current Season 1
//              collectible-document locations, refreshed from the attributed
//              community dataset with `npm run update:intel`.
//
//   prebaked  src/data/prebaked/intel.json — loose-loot positions for the older
//             intel items, in game-world x/y/z. Generated by scripts/prebake.mjs
//             from upstream `lootLoose`. Zero curation, and the coordinates are
//             the same space PMC spawns and position pings already use, so there
//             is no calibration anywhere in this file.
//
//   curated   the `map_loot` table — hand-placed points for the Season 1 document
//             items, which upstream has *no* coordinates for (see
//             docs/archive/IMPLEMENTATION-PLAN.md line 205). Stored normalised 0-1 against the
//             map image exactly like `map_keys`, so they have to be projected into
//             world coordinates before they can sit alongside the prebaked ones.
//
// A normalised point has no height, so `y` is null on curated points and every
// consumer must treat a floor badge as optional.

import { TARKOV_MAP_CONFIGS } from './data/tarkovMapConfigs'
import { compassDir } from './tarkovPings'

export const INTEL_FOLDER = 'Intelligence folder'
export const INTEL_CASE   = 'Documents case'

// Points closer than this are the same physical spawn as far as a reader is
// concerned — upstream lists several rolls a couple of metres apart inside one
// filing cabinet. Merging them stops the map showing a smear of stacked icons
// where there is really one place to walk to.
const MERGE_RADIUS_M = 4

// How far out a nearest-spawn callout is still information rather than noise.
export const NEAR_RADIUS_M  = 250
// "Two more within X" in the ping callout.
export const CLUSTER_RADIUS_M = 60

export const INTEL_KINDS = {
  folder:   { key: 'folder',   label: 'Intelligence folder', color: '#6a9aaa', short: 'FOLDER' },
  case:     { key: 'case',     label: 'Documents case',      color: '#5db8e8', short: 'CASE' },
  document: { key: 'document', label: 'Document',            color: '#c9a84c', short: 'DOC' },
  battlepass: { key: 'battlepass', label: 'Battle Pass Intel', color: '#c9a84c', short: 'INTEL' },
}

// Curated rows carry their own loot_type; anything unrecognised renders as a
// document rather than being dropped, because an admin typo should not make a
// hand-placed point invisible.
export function kindOf(point) {
  return INTEL_KINDS[point?.kind] || INTEL_KINDS.document
}

/**
 * Project a normalised 0-1 map-image coordinate into game-world x/z.
 *
 * This is `normToLatlng` from MapLeaflet written against the raw config instead
 * of a Leaflet bounds object, so that proximity maths can run outside the map
 * component. lat is z, lng is x — the same convention as `getBounds`.
 */
export function normToWorld(normX, normY, mapNorm) {
  const cfg = TARKOV_MAP_CONFIGS[mapNorm]
  if (!cfg || !Number.isFinite(normX) || !Number.isFinite(normY)) return null
  const minX = Math.min(cfg.bounds[0][0], cfg.bounds[1][0])
  const maxX = Math.max(cfg.bounds[0][0], cfg.bounds[1][0])
  const minZ = Math.min(cfg.bounds[0][1], cfg.bounds[1][1])
  const maxZ = Math.max(cfg.bounds[0][1], cfg.bounds[1][1])
  return {
    x: minX + normX * (maxX - minX),
    z: minZ + (1 - normY) * (maxZ - minZ),
  }
}

// The inverse — used by the admin editor to show where a prebaked point sits on
// the flat map image it places curated points against.
export function worldToNorm(x, z, mapNorm) {
  const cfg = TARKOV_MAP_CONFIGS[mapNorm]
  if (!cfg || !Number.isFinite(x) || !Number.isFinite(z)) return null
  const minX = Math.min(cfg.bounds[0][0], cfg.bounds[1][0])
  const maxX = Math.max(cfg.bounds[0][0], cfg.bounds[1][0])
  const minZ = Math.min(cfg.bounds[0][1], cfg.bounds[1][1])
  const maxZ = Math.max(cfg.bounds[0][1], cfg.bounds[1][1])
  if (maxX === minX || maxZ === minZ) return null
  return {
    nx: (x - minX) / (maxX - minX),
    ny: 1 - (z - minZ) / (maxZ - minZ),
  }
}

// Stable across reloads and across the prebake refreshing intel.json, as long as
// the position does not move: the checklist is keyed on this, and a key that
// changed every build would silently un-check everything on deploy day.
export function intelPointId(point) {
  if (point.sourceRef) return `${point.source}:${point.map}:${point.sourceRef}`
  const parts = [point.source, point.map, point.x.toFixed(1), point.z.toFixed(1)]
  return parts.join(':')
}

/** Shape the current Battle Pass community dataset for one map. */
export function battlepassIntelPoints(data, mapNorm) {
  if (!Array.isArray(data) || !mapNorm) return []
  const entry = data.find(map => map?.normalizedName === mapNorm)
  if (!entry || !Array.isArray(entry.points)) return []

  return entry.points.flatMap(point => {
    const world = normToWorld(point?.locX, point?.locY, mapNorm)
    if (!world || typeof point.documentType !== 'string') return []
    const shaped = {
      source: 'battlepass',
      sourceRef: point.sourceRef,
      map: mapNorm,
      x: world.x,
      y: null,
      z: world.z,
      items: [point.documentType],
      kind: 'battlepass',
      name: point.title || point.documentType,
      notes: [point.title, point.notes, point.requires ? `REQUIRES ${point.requires}` : null]
        .filter(Boolean).join(' — '),
    }
    return [{ ...shaped, id: intelPointId(shaped) }]
  })
}

function mergeNearby(points) {
  const out = []
  for (const p of points) {
    const near = out.find(o => Math.hypot(o.x - p.x, o.z - p.z) < MERGE_RADIUS_M)
    if (!near) { out.push({ ...p, items: [...p.items] }); continue }
    for (const item of p.items) if (!near.items.includes(item)) near.items.push(item)
    if (near.kind === 'folder' && p.kind === 'case') near.kind = 'case'
  }
  return out
}

/**
 * Shape the prebaked `intel.json` payload for one map.
 *
 * @param  {Array}  data     the `data` array from intel.json
 * @param  {string} mapNorm
 * @returns {Array} points, merged and id'd
 */
export function prebakedIntelPoints(data, mapNorm) {
  if (!Array.isArray(data) || !mapNorm) return []
  const entry = data.find(m => m?.normalizedName === mapNorm)
  if (!entry || !Array.isArray(entry.points)) return []

  const raw = []
  for (const p of entry.points) {
    const pos = p?.position
    if (!pos || !Number.isFinite(pos.x) || !Number.isFinite(pos.z)) continue
    const items = Array.isArray(p.items) ? p.items.filter(i => typeof i === 'string') : []
    if (!items.length) continue
    raw.push({
      source: 'intel',
      map: mapNorm,
      x: pos.x,
      y: Number.isFinite(pos.y) ? pos.y : null,
      z: pos.z,
      items,
      // A point that can roll the case is worth more than one that cannot, so
      // that is what the icon says when a point can roll both.
      kind: items.includes(INTEL_CASE) ? 'case' : 'folder',
      name: items.includes(INTEL_CASE) ? INTEL_CASE : INTEL_FOLDER,
      notes: null,
    })
  }
  return mergeNearby(raw).map(p => ({ ...p, id: intelPointId(p) }))
}

/**
 * Shape `map_loot` rows for one map. Rows without coordinates are dropped —
 * they are a half-finished admin entry, not a spawn.
 */
export function curatedLootPoints(rows, mapNorm) {
  if (!Array.isArray(rows) || !mapNorm) return []
  const out = []
  for (const row of rows) {
    if (row?.map_norm !== mapNorm) continue
    if (row.loc_x == null || row.loc_y == null) continue
    const world = normToWorld(row.loc_x, row.loc_y, mapNorm)
    if (!world) continue
    const point = {
      source: 'loot',
      rowId: row.id,
      map: mapNorm,
      x: world.x,
      // Curated points are placed on a flat image and carry no height, so no
      // floor badge is possible for them. Null, never a guessed zero.
      y: null,
      z: world.z,
      items: [row.loot_name],
      kind: INTEL_KINDS[row.loot_type] ? row.loot_type : 'document',
      name: row.loot_name,
      notes: row.notes || null,
    }
    out.push({ ...point, id: intelPointId(point) })
  }
  return out
}

// Prebaked first so curated points draw on top of them.
export function mergeIntelSources(prebaked, curated) {
  return [...prebaked, ...curated]
}

export function countByKind(points) {
  const counts = { folder: 0, case: 0, document: 0, battlepass: 0 }
  for (const p of points) counts[kindOf(p).key] += 1
  return counts
}

// ─── Planning rings — Phase 8 ────────────────────────────────────────────────
//
// The pre-raid half of "radius rings on the map for planning". The in-raid half
// is the nearest-spawn callout below, which needs a position and therefore a
// ping; rings need nothing and can be read before you queue.
//
// The radii are the two numbers the rest of the feature already uses plus one
// in between, so a ring means the same thing as the callout that quotes it:
// 60 m is CLUSTER_RADIUS_M ("2 more within 60 m"), 250 m is NEAR_RADIUS_M (the
// cut-off past which a callout is noise).
export const RING_RADII_M = [60, 120, 250]

const RING_SEGMENTS = 48

/**
 * A world-space circle as an explicit polygon in Leaflet [lat, lng] order —
 * which is [z, x] here, the same convention as every other placement.
 *
 * Not `L.circle`: that asks Leaflet to derive one pixel radius by projecting a
 * single offset point, which is only a circle if the CRS scales both axes
 * equally, and these maps run that projection through a rotation as well.
 * Emitting the points ourselves is exact under any transform and costs 48
 * multiplies.
 */
export function ringPath(x, z, radius, segments = RING_SEGMENTS) {
  if (!Number.isFinite(x) || !Number.isFinite(z) || !(radius > 0)) return []
  const pts = []
  for (let i = 0; i < segments; i++) {
    const a = (i / segments) * Math.PI * 2
    pts.push([z + radius * Math.sin(a), x + radius * Math.cos(a)])
  }
  return pts
}

/**
 * For each unchecked point, how many unchecked points lie within `radius` of it
 * — itself included, so the number reads as "spawns covered by standing here".
 *
 * O(n²) on at most 64 points. Deliberately not a clustering algorithm: the
 * question is "how much does one detour buy me", and every candidate detour is
 * a spawn you were going to walk to anyway.
 */
export function clusterCounts(points, radius, isChecked) {
  const live = (points || []).filter(p => !(isChecked && isChecked(p.id)))
  const counts = new Map()
  for (const p of live) {
    let n = 0
    for (const q of live) if (Math.hypot(q.x - p.x, q.z - p.z) <= radius) n += 1
    counts.set(p.id, n)
  }
  return counts
}

// The densest group — the one worth planning a route around. Null when every
// point is checked or there are none.
export function bestCluster(points, radius, isChecked) {
  const counts = clusterCounts(points, radius, isChecked)
  let best = null
  for (const p of points || []) {
    const count = counts.get(p.id)
    if (count == null) continue
    if (!best || count > best.count) best = { point: p, count }
  }
  return best
}

/**
 * Nearest point to a position, and how many others are close behind it.
 *
 * `from` is anything with world x/z — a ping, in practice. `isChecked` lets the
 * caller exclude spawns the player has already cleared this raid, which is the
 * whole point of the callout: "nearest *unchecked* document spawn".
 */
export function nearestIntel(from, points, isChecked) {
  if (!from || !Array.isArray(points) || !points.length) return null
  let best = null
  let within = 0
  for (const p of points) {
    if (isChecked && isChecked(p.id)) continue
    const dx = p.x - from.x
    const dz = p.z - from.z
    const dist = Math.hypot(dx, dz)
    if (!Number.isFinite(dist)) continue
    if (dist <= CLUSTER_RADIUS_M) within += 1
    if (!best || dist < best.dist) best = { point: p, dist, dir: compassDir(dx, dz) }
  }
  if (!best || best.dist > NEAR_RADIUS_M) return null
  return {
    point: best.point,
    dist: Math.round(best.dist),
    dir: best.dir,
    // The nearest one is itself inside the cluster radius when it is close, so
    // "more" has to exclude it or the count reads one too high.
    more: Math.max(0, within - (best.dist <= CLUSTER_RADIUS_M ? 1 : 0)),
  }
}
